# A TOML plugin for proto:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "act"
type = "cli"

[platform.linux]
download-file = "act_Linux_{arch}.tar.gz"
bin-path = "act"
checksum-file = "checksums.txt"

[platform.macos]
download-file = "act_Darwin_{arch}.tar.gz"
bin-path = "act"
checksum-file = "checksums.txt"

[platform.windows]
download-file = "act_Windows_{arch}.zip"
bin-path = "act.exe"
checksum-file = "checksums.txt"

[install]
download-url = "https://github.com/nektos/act/releases/download/v{version}/{download_file}"
checksum-url = "https://github.com/nektos/act/releases/download/v{version}/{checksum_file}"
unpack = false

[install.arch]
aarch64 = "arm64"
arm = "armv7"
x86 = "i386"

[resolve]
git-url = "https://github.com/nektos/act"
